fix: Hugo debug flag has been removed
```shell
$ docker run \
        --rm -it --entrypoint hugo \
        docker.io/grafana/docs-base:latest \
        help | grep debug
      --logLevel string            log level (debug|info|warn|error)
```

Without this change the make target errors:

```shell
$ make docs-debug
WEBSITE_EXEC='hugo server --bind 0.0.0.0 --port 3002 --debug' <snip>
<snip>

Use "hugo server [command] --help" for more information about a command.

Error: command error: unknown flag: --debug
make: *** [docs.mk:100: docs-debug] Error 1
```